apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
  namespace: default
spec:
  # image: if you are using a new version of cockroach you need this
  #   name: cockroachdb/cockroach:v21.1.7
  tlsEnabled: false
  nodes: 2
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem