apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: default
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev

# apiVersion: apps.open-cluster-management.io/v1
# kind: PlacementRule
# metadata:
#   name: us-east-1-clusters
#   namespace: default
# spec:
#   clusterConditions:
#     - type: ManagedClusterConditionAvailable
#       status: "True"
#   clusterSelector:
#     matchLabels:
#       region: us-east-1
