---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: argocd-app-latest
  namespace: argocd
spec:
  type: GitHub
  pathname: https://github.com/cmwylie19/bookinfo-acm.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - argocd-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: argocd-app
  namespace: argocd
  labels:
    app: argocd-app
  annotations:
    apps.open-cluster-management.io/github-path: resources/argocd
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: argocd/argocd-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: all-dev-clusters

