apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-dev-clusters
  namespace: argocd
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      env: dev

